"""full schema with course orchestrator

Revision ID: 031a92ead68d
Revises: a1b2c3d4e5f6
Create Date: 2026-02-18 11:37:10.457221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '031a92ead68d'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hotmart_product_id', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_hotmart_product_id'), 'products', ['hotmart_product_id'], unique=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PROFESSOR', 'STUDENT', 'TA', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hotmart_id', sa.String(length=255), nullable=True),
    sa.Column('discord_id', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('PENDING_PAYMENT', 'PENDING_ONBOARDING', 'ACTIVE', 'CHURNED', name='lifecyclestatus'), nullable=True),
    sa.Column('onboarding_token', sa.String(length=16), nullable=True),
    sa.Column('onboarding_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manychat_subscriber_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_hotmart_id'), 'users', ['hotmart_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_onboarding_token'), 'users', ['onboarding_token'], unique=True)
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_index(op.f('ix_classes_invite_code'), 'classes', ['invite_code'], unique=True)
    op.create_index(op.f('ix_classes_professor_id'), 'classes', ['professor_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PROCESSED', 'FAILED', 'IGNORED', name='eventstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_actor_id'), 'events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_target_id'), 'events', ['target_id'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('template_code', sa.Text(), nullable=True),
    sa.Column('language', sa.Enum('PYTHON', name='programminglanguage'), nullable=False),
    sa.Column('submission_type', sa.Enum('CODE', 'FILE_UPLOAD', name='submissiontype'), nullable=False),
    sa.Column('grading_mode', sa.Enum('TEST_FIRST', 'LLM_FIRST', name='gradingmode'), nullable=False),
    sa.Column('max_submissions', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=False),
    sa.Column('has_tests', sa.Boolean(), nullable=False),
    sa.Column('llm_grading_enabled', sa.Boolean(), nullable=False),
    sa.Column('test_weight', sa.Float(), nullable=False),
    sa.Column('llm_weight', sa.Float(), nullable=False),
    sa.Column('llm_grading_criteria', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_created_by'), 'exercises', ['created_by'], unique=False)
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_table('product_access_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('DISCORD_ROLE', 'CLASS_ENROLLMENT', 'MANYCHAT_TAG', name='accessruletype'), nullable=False),
    sa.Column('rule_value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_access_rules_id'), 'product_access_rules', ['id'], unique=False)
    op.create_index(op.f('ix_product_access_rules_product_id'), 'product_access_rules', ['product_id'], unique=False)
    op.create_table('class_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enrollment_source', sa.Enum('MANUAL', 'PRODUCT', name='enrollmentsource'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'student_id', name='uq_class_student')
    )
    op.create_index('ix_class_enrollments_class_student', 'class_enrollments', ['class_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_class_enrollments_id'), 'class_enrollments', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_class_id'), 'groups', ['class_id'], unique=False)
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('rubric_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubric_dimensions_exercise_id'), 'rubric_dimensions', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_rubric_dimensions_id'), 'rubric_dimensions', ['id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='submissionstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_content_hash'), 'submissions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_submissions_exercise_id'), 'submissions', ['exercise_id'], unique=False)
    op.create_index('ix_submissions_exercise_student_submitted', 'submissions', ['exercise_id', 'student_id', 'submitted_at'], unique=False)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_exercise_id'), 'test_cases', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_test_cases_id'), 'test_cases', ['id'], unique=False)
    op.create_table('exercise_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('opens_at', sa.Integer(), nullable=True),
    sa.Column('closes_at', sa.Integer(), nullable=True),
    sa.Column('late_penalty_percent_per_day', sa.Float(), nullable=True),
    sa.Column('auto_publish_grades', sa.Boolean(), nullable=False),
    sa.Column('randomize_order', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_lists_class_id'), 'exercise_lists', ['class_id'], unique=False)
    op.create_index(op.f('ix_exercise_lists_group_id'), 'exercise_lists', ['group_id'], unique=False)
    op.create_index(op.f('ix_exercise_lists_id'), 'exercise_lists', ['id'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('test_score', sa.Float(), nullable=True),
    sa.Column('llm_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('late_penalty_applied', sa.Float(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_id'), 'grades', ['id'], unique=False)
    op.create_index(op.f('ix_grades_submission_id'), 'grades', ['submission_id'], unique=True)
    op.create_table('group_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_memberships_group_id'), 'group_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_memberships_id'), 'group_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_group_memberships_student_id'), 'group_memberships', ['student_id'], unique=False)
    op.create_table('llm_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_evaluations_content_hash'), 'llm_evaluations', ['content_hash'], unique=False)
    op.create_index(op.f('ix_llm_evaluations_id'), 'llm_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_llm_evaluations_submission_id'), 'llm_evaluations', ['submission_id'], unique=True)
    op.create_table('rubric_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dimension_id'], ['rubric_dimensions.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'dimension_id', name='uq_rubric_score_submission_dimension')
    )
    op.create_index(op.f('ix_rubric_scores_dimension_id'), 'rubric_scores', ['dimension_id'], unique=False)
    op.create_index(op.f('ix_rubric_scores_id'), 'rubric_scores', ['id'], unique=False)
    op.create_index(op.f('ix_rubric_scores_submission_id'), 'rubric_scores', ['submission_id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    op.create_index(op.f('ix_test_results_submission_id'), 'test_results', ['submission_id'], unique=False)
    op.create_table('exercise_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['exercise_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_list_items_exercise_id'), 'exercise_list_items', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_list_items_id'), 'exercise_list_items', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_list_items_list_id'), 'exercise_list_items', ['list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_list_items_list_id'), table_name='exercise_list_items')
    op.drop_index(op.f('ix_exercise_list_items_id'), table_name='exercise_list_items')
    op.drop_index(op.f('ix_exercise_list_items_exercise_id'), table_name='exercise_list_items')
    op.drop_table('exercise_list_items')
    op.drop_index(op.f('ix_test_results_submission_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_rubric_scores_submission_id'), table_name='rubric_scores')
    op.drop_index(op.f('ix_rubric_scores_id'), table_name='rubric_scores')
    op.drop_index(op.f('ix_rubric_scores_dimension_id'), table_name='rubric_scores')
    op.drop_table('rubric_scores')
    op.drop_index(op.f('ix_llm_evaluations_submission_id'), table_name='llm_evaluations')
    op.drop_index(op.f('ix_llm_evaluations_id'), table_name='llm_evaluations')
    op.drop_index(op.f('ix_llm_evaluations_content_hash'), table_name='llm_evaluations')
    op.drop_table('llm_evaluations')
    op.drop_index(op.f('ix_group_memberships_student_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_group_id'), table_name='group_memberships')
    op.drop_table('group_memberships')
    op.drop_index(op.f('ix_grades_submission_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_exercise_lists_id'), table_name='exercise_lists')
    op.drop_index(op.f('ix_exercise_lists_group_id'), table_name='exercise_lists')
    op.drop_index(op.f('ix_exercise_lists_class_id'), table_name='exercise_lists')
    op.drop_table('exercise_lists')
    op.drop_index(op.f('ix_test_cases_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_exercise_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index('ix_submissions_exercise_student_submitted', table_name='submissions')
    op.drop_index(op.f('ix_submissions_exercise_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_content_hash'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_rubric_dimensions_id'), table_name='rubric_dimensions')
    op.drop_index(op.f('ix_rubric_dimensions_exercise_id'), table_name='rubric_dimensions')
    op.drop_table('rubric_dimensions')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_class_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_class_enrollments_id'), table_name='class_enrollments')
    op.drop_index('ix_class_enrollments_class_student', table_name='class_enrollments')
    op.drop_table('class_enrollments')
    op.drop_index(op.f('ix_product_access_rules_product_id'), table_name='product_access_rules')
    op.drop_index(op.f('ix_product_access_rules_id'), table_name='product_access_rules')
    op.drop_table('product_access_rules')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_created_by'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_target_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index(op.f('ix_events_actor_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_classes_professor_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_invite_code'), table_name='classes')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_users_onboarding_token'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_hotmart_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_hotmart_product_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
