"""add phone to hotmart_buyers

Revision ID: 360fa80e3ebd
Revises: 5b300c4ab8b4
Create Date: 2026-02-21 12:41:08.106254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360fa80e3ebd'
down_revision: Union[str, None] = '5b300c4ab8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotmart_buyers', sa.Column('phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotmart_buyers', 'phone')
    # ### end Alembic commands ###
