"""add hotmart_buyers and hotmart_product_mapping

Revision ID: 5b300c4ab8b4
Revises: 8627e866ab3d
Create Date: 2026-02-21 09:25:54.147176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b300c4ab8b4'
down_revision: Union[str, None] = '8627e866ab3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotmart_buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('hotmart_product_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'hotmart_product_id', name='uq_hotmart_buyers_email_product')
    )
    op.create_index(op.f('ix_hotmart_buyers_email'), 'hotmart_buyers', ['email'], unique=False)
    op.create_index(op.f('ix_hotmart_buyers_id'), 'hotmart_buyers', ['id'], unique=False)
    op.create_index(op.f('ix_hotmart_buyers_user_id'), 'hotmart_buyers', ['user_id'], unique=False)
    op.create_table('hotmart_product_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_hotmart_product_id', sa.String(length=255), nullable=False),
    sa.Column('target_product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hotmart_product_id', 'target_product_id', name='uq_hotmart_product_mapping_source_target')
    )
    op.create_index(op.f('ix_hotmart_product_mapping_id'), 'hotmart_product_mapping', ['id'], unique=False)
    op.create_index(op.f('ix_hotmart_product_mapping_source_hotmart_product_id'), 'hotmart_product_mapping', ['source_hotmart_product_id'], unique=False)
    op.create_index(op.f('ix_hotmart_product_mapping_target_product_id'), 'hotmart_product_mapping', ['target_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotmart_product_mapping_target_product_id'), table_name='hotmart_product_mapping')
    op.drop_index(op.f('ix_hotmart_product_mapping_source_hotmart_product_id'), table_name='hotmart_product_mapping')
    op.drop_index(op.f('ix_hotmart_product_mapping_id'), table_name='hotmart_product_mapping')
    op.drop_table('hotmart_product_mapping')
    op.drop_index(op.f('ix_hotmart_buyers_user_id'), table_name='hotmart_buyers')
    op.drop_index(op.f('ix_hotmart_buyers_id'), table_name='hotmart_buyers')
    op.drop_index(op.f('ix_hotmart_buyers_email'), table_name='hotmart_buyers')
    op.drop_table('hotmart_buyers')
    # ### end Alembic commands ###
