"""add student_course_status scd2

Revision ID: 7af56f19e432
Revises: 031a92ead68d
Create Date: 2026-02-19 08:05:59.896426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af56f19e432'
down_revision: Union[str, None] = '031a92ead68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_course_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_course_status_current', 'student_course_status', ['user_id', 'product_id'], unique=False, postgresql_where=sa.text('is_current = true'))
    op.create_index(op.f('ix_student_course_status_id'), 'student_course_status', ['id'], unique=False)
    op.create_index(op.f('ix_student_course_status_product_id'), 'student_course_status', ['product_id'], unique=False)
    op.create_index(op.f('ix_student_course_status_user_id'), 'student_course_status', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_course_status_user_id'), table_name='student_course_status')
    op.drop_index(op.f('ix_student_course_status_product_id'), table_name='student_course_status')
    op.drop_index(op.f('ix_student_course_status_id'), table_name='student_course_status')
    op.drop_index('ix_student_course_status_current', table_name='student_course_status', postgresql_where=sa.text('is_current = true'))
    op.drop_table('student_course_status')
    # ### end Alembic commands ###
