"""Add message_campaigns and message_recipients tables

Revision ID: d42982779265
Revises: 360fa80e3ebd
Create Date: 2026-02-22 18:00:32.382487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42982779265'
down_revision: Union[str, None] = '360fa80e3ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('course_name', sa.String(length=255), nullable=True),
    sa.Column('sent_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SENDING', 'COMPLETED', 'PARTIAL_FAILURE', 'FAILED', name='campaignstatus'), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_campaigns_created_at'), 'message_campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_campaigns_id'), 'message_campaigns', ['id'], unique=False)
    op.create_table('message_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('resolved_message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='recipientstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['message_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_recipients_campaign_id'), 'message_recipients', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_message_recipients_id'), 'message_recipients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_recipients_id'), table_name='message_recipients')
    op.drop_index(op.f('ix_message_recipients_campaign_id'), table_name='message_recipients')
    op.drop_table('message_recipients')
    op.drop_index(op.f('ix_message_campaigns_id'), table_name='message_campaigns')
    op.drop_index(op.f('ix_message_campaigns_created_at'), table_name='message_campaigns')
    op.drop_table('message_campaigns')
    # ### end Alembic commands ###
